// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMkCKHkfrY9AhOM_KzacrkyyYD-8ByIp0',
    appId: '1:992000671800:web:841968101f0141ec4ae6cd',
    messagingSenderId: '992000671800',
    projectId: 'paysnap-e5617',
    authDomain: 'paysnap-e5617.firebaseapp.com',
    storageBucket: 'paysnap-e5617.appspot.com',
    measurementId: 'G-62ND1RW4TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99BKV2ENJTBKcrz3WBdgc4rkR1S8PPUg',
    appId: '1:992000671800:android:e6e0e5216d201b474ae6cd',
    messagingSenderId: '992000671800',
    projectId: 'paysnap-e5617',
    storageBucket: 'paysnap-e5617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBATiBAnhSN2O0xSr-yfPFnSt6e1TMr6XM',
    appId: '1:992000671800:ios:e0a80e1242b8131e4ae6cd',
    messagingSenderId: '992000671800',
    projectId: 'paysnap-e5617',
    storageBucket: 'paysnap-e5617.appspot.com',
    iosBundleId: 'com.payment.paysnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBATiBAnhSN2O0xSr-yfPFnSt6e1TMr6XM',
    appId: '1:992000671800:ios:c15f3cb82005f6704ae6cd',
    messagingSenderId: '992000671800',
    projectId: 'paysnap-e5617',
    storageBucket: 'paysnap-e5617.appspot.com',
    iosBundleId: 'com.payment.paysnap.RunnerTests',
  );
}
